// Type declarations for WebAssembly module generated by wasm-pack
declare module '/wasm/website_wasm.js' {
  export default function init(input?: RequestInfo | URL | Response | BufferSource | WebAssembly.Module): Promise<void>;
  
  export function greet(name: string): string;
  export function fibonacci(n: number): bigint;
  export function is_prime(n: bigint): boolean;
  export function generate_primes(limit: bigint): BigUint64Array;
  export function factorial(n: bigint): bigint;
  export function hash_string(input: string): bigint;
  export function utf8_byte_count(text: string): number;
  export function unicode_char_count(text: string): number;
  export function analyze_string(text: string): StringAnalysis;
  export function performance_test(iterations: number): number;
  
  export class StringAnalysis {
    constructor();
    readonly byte_count: number;
    readonly char_count: number;
    readonly word_count: number;
    readonly line_count: number;
  }
}

// Make WASM files importable
declare module '*.wasm' {
  const content: WebAssembly.Module;
  export default content;
}
